char *config_command( char *command, sqlite3 *database );
char *execute_command( char *command, sqlite3 *database );
char insertRequest( char *correct, insert_t insert, char *insert_into );
int prompt( char *command, char *command_text );
int get_update_command( char *command, char *command_text );
void print_help( void );
int print_stats( char *command, sqlite3 *database );
char *myselect( char *command, sqlite3 *database );
int read_file( char *command, sqlite3 *database );
int read_DNB( FILE *fp, sqlite3 *database, int skip_counter );
int read_SBS( FILE *fp, sqlite3 *database, int skip_counter );
int update( char *command, sqlite3 *database );
