char *config_command(char *command, sqlite3 *database);
char *execute_command(char *command, sqlite3 *database);
int get_command(char *command, char *command_text);
int get_update_command(char *command, char *command_text);
void print_help(char *command);
int print_stats(char *command, sqlite3 *database);
char *myselect(char *command, sqlite3 *database);
int read_file(char *command, sqlite3 *database);
int read_DNB(FILE *fp, sqlite3 *database);
int read_SBS(FILE *fp, sqlite3 *database);
int update(char *command, sqlite3 *database);
